### ISSUE TITLE
What's usage to work

### ISSUE THREAD

**Issue by Epipong** [YiuRULE/Generic-list#1]
I have problems to work correctly your list and I have following error message at compiled time:
`➜  Generic-list git:(master) ✗ clang test.c`
`test.c:8:3: error: use of undeclared identifier 'ExgSOXJ7r_int'`
`LIST(int)     a;`

`````` ^```
```./generic_list.h:33:21: note: expanded from macro 'LIST'```
```\# define LIST(type) M_CONC(STRING_TYPE, type)```
```                    ^```
```./generic_list.h:16:22: note: expanded from macro 'M_CONC'```
```#define M_CONC(A, B) M_CONC_(A, B)```
```                     ^```
```./generic_list.h:17:23: note: expanded from macro 'M_CONC_'```
```#define M_CONC_(A, B) A##B```
```                      ^```
```<scratch space>:17:1: note: expanded from here```
```ExgSOXJ7r_int```
```^```
```1 error generated.```
``````

**Comment by YiuRULE** [comment]
When used the LIST macro, you should always use the CREATE_TYPE_LIST macro.

If you don't do that, your compiler doesn't know what's the type you actually call.

Here the example code, you can also find it in the generic_list.h file.

```
CREATE_TYPE_LIST(int)

int main(int ac, char **av)
{
    LIST(int) *a = malloc(sizeof(LIST(int)));
}
```

**Comment by Epipong** [comment]
My bad, but I suggest you to add in README.md ;)
Have a good day
